name: TIE
channels:
  - swisstopo
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1
  - affine=2.4.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.8
  - aiosignal=1.3.1
  - aom=3.9.1
  - appdirs=1.4.4
  - apptools=5.1.0
  - archspec=0.2.3
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - black=24.8.0
  - blosc=1.21.6
  - bokeh=3.4.2
  - boltons=24.0.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.15.1
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=4.4.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - conda=24.9.1
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - configobj=5.0.9
  - contourpy=1.3.0
  - cycler=0.12.1
  - cytoolz=1.0.0
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - dav1d=1.2.1
  - decorator=5.1.1
  - distributed=2024.8.0
  - distro=1.9.0
  - double-conversion=3.3.0
  - eigen=3.4.0
  - envisage=6.0.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=6.1.2
  - flake8=7.1.1
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozendict=2.4.4
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - gdal=3.8.4
  - geocover_utils=0.4.0
  - geocube=0.4.2
  - geojson=3.1.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.12.1
  - geotiff=1.7.1
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.5
  - gstreamer=1.24.5
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - imagecodecs=2024.6.1
  - imageio=2.35.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2024.2.1
  - ipycytoscape=1.3.3
  - ipython=8.18.1
  - ipywidgets=8.1.5
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsoncpp=1.9.5
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - kealib=1.5.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgdal=3.8.4
  - libglib=2.80.2
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libmamba=1.5.10
  - libmambapy=1.5.10
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsolv=0.7.30
  - libspatialite=5.1.0
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtheora=1.1.1
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzip=1.11.1
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - locket=1.0.0
  - loguru=0.7.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mamba=1.5.10
  - mapclassify=2.8.1
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mayavi=4.8.2
  - mccabe=0.7.0
  - menuinst=2.1.2
  - minizip=4.0.6
  - mkl=2024.1.0
  - msgpack-python=1.1.0
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - networkx=3.2.1
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - odc-geo=0.4.8
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.0
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.12.1
  - pcre2=10.43
  - pep8-naming=0.14.1
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - ply=3.11
  - poppler=24.03.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - proj=9.3.1
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pyface=8.0.0
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pyogrio=0.7.2
  - pyparsing=3.1.4
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - qt6-main=6.7.2
  - rasterio=1.3.9
  - rav1e=0.6.6
  - re2=2023.09.01
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - rioxarray=0.15.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruff=0.6.9
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - setuptools=75.1.0
  - shapely=2.0.4
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - spdlog=1.13.0
  - spectate=1.0.1
  - sqlite=3.46.1
  - stack_data=0.6.2
  - svt-av1=2.2.1
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tblib=3.0.0
  - threadpoolctl=3.5.0
  - tietoolbox=0.4.11
  - tifffile=2024.6.18
  - tiledb=2.21.2
  - tk=8.6.13
  - tomli=2.0.2
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - traits=6.4.3
  - traitsui=8.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - untie=0.0.8
  - uriparser=0.9.8
  - urllib3=2.2.3
  - utfcpp=4.0.5
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - vtk=9.3.0
  - vtk-base=9.3.0
  - wcwidth=0.2.13
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - wslink=2.2.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2024.7.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.40.1
  - yarl=1.13.1
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
