name: Build Windows Conda env

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  conda-env:
    name: Windows Conda env for TIE
    runs-on: "windows-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: TIE
          python-version: 3.9.18
          channels: swisstopo,conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - shell: bash -el {0}
        name: Bash
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Build install
        shell: bash -el {0}
        run: |
          conda install --channel conda-forge conda-build anaconda-client conda-verify
          conda install -c swisstopo -c conda-forge -c esri geocube geopandas matplotlib mayavi numpy rasterio scipy "shapely>=2.0.0"  scikit-image dask
          conda build --help
          python -c "import os; print(os.listdir())"
          conda info
          conda list
          conda env export
      - name: Upload Compressed conda env
        uses: actions/upload-artifact@v4
        with:
          name: conda-envs-$CONDA_DEFAULT_ENV.zip
          path: $CONDA_PREFIX 
          compression-level: 5
          
          
      
 
