name: Build Conda Package for many OS

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9.18 # Set the specific Python version
          auto-update-conda: false
          activate-environment: TIE
          channels: swisstopo,conda-forge  # default is included
          channel-priority: flexible
          environment-file: environment.yaml
      - shell: bash -l {0}
        name: Install packages for building
        run: |
          conda install  -c conda-forge mamba conda-build anaconda-client conda-verify 
          conda info
          conda list

      - name: Check installation
        shell: bash -l {0}
        run: |
          conda build --help
          conda info
          conda list
          echo $env:CONDA_PREFIX
          
      - name: Set Package Version
        shell: bash -l {0}
        run: |
          echo "version=$(<toolbox/VERSION)" >> $GITHUB_ENV
          echo "=== PKG_VERSION=$version ==="
          
      
         
      - name: Build Conda Package
        shell: bash -l {0}
        run: |
          conda build -c swisstopo -c conda-forge  recipe
          echo "PACKAGE_PATH=$(conda build  --output recipe)" >> $GITHUB_ENV
          echo "=== PACKAGE_PATH=$PACKAGE_PATH ==="
          
  

      - name: Upload Conda Package to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  tietoolbox-${{ env.version }}-${{ matrix.os }}-py39_0.tar.bz2
          path:   ${{ env.PACKAGE_PATH }} 
          compression-level: 0 # no compression
          
    


