name: conda build windows

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - 'develop'
    tags:
      - '*'
    
jobs:
  example-2-win:
    name: Windows only
    runs-on: "windows-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: TIE
          python-version: 3.9
          channels: swisstopo,conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: PowerShell
        shell: powershell
        run: |
          conda info
          conda list
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Cmd.exe
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list &&
          conda install --channel conda-forge conda-build anaconda-client conda-verify  &&
          conda build --help
          python -c "import os; print(os.listdir())"
      - name: Initialize Conda for Powershell
        shell: pwsh
        run: |
           conda install --channel conda-forge conda-build anaconda-client conda-verify
           conda build --help
           conda-build --debug -c swisstopo  -c esri -c conda-forge  ..\recipe\meta.yaml
 
