name: Build Conda Package

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - develop2

jobs:
  build:
    runs-on: windows-latest  # Only run on Windows

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9.18 # Set the specific Python version
          auto-update-conda: false  # no update
          activate-environment: TIE
          channels: swisstopo,conda-forge  # default is included
          channel-priority: flexible

      - name: Install Dependencies
        run: conda env update --file environment.yaml --prune
          
      - name: Conda in PowerShell
        shell: powershell
        run: |
          conda install -n base -c conda-forge mamba
          conda info
          conda list
      - name: Install packages in PowerShell Core
        shell: pwsh
        run: |
          conda install --channel conda-forge conda-build anaconda-client conda-verify 
          conda install --channel conda-forge  geocube geopandas matplotlib mayavi numpy rasterio scipy "shapely>=2.0.0"  scikit-image dask
          conda build --help
          conda info
          conda list
          echo $env:CONDA_PREFIX
          
      - name: Set Package Version
        shell: pwsh
        run: |
          $version = Get-Content toolbox/VERSION
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "=== PKG_VERSION=$version ==="
          
          
      - name: Build Conda Package
        shell: pwsh
        run: |
          conda build -c swisstopo -c conda-forge  recipe
          $PACKAGE_PATH = conda build  --output recipe
          echo "PACKAGE_PATH=$PACKAGE_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "=== PACKAGE_PATH=$PACKAGE_PATH ==="
          
      - name: Toying with Bash
        shell: bash
        run: |
            echo "version=$(<toolbox/VERSION)" >> $GITHUB_ENV
   

      - name: Upload Conda Package to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  tietoolbox-${{ env.version }}-py39_0.tar.bz2
          path:   ${{ env.PACKAGE_PATH }} 
          compression-level: 0 # no compression
          
    
      - name: Test Conda Package Installation
        run: |
          mamba create -n test-env python=3.9.18 geocube geopandas matplotlib mayavi numpy rasterio scipy
          mamba activate test-env
          mamba install --use-local tietoolbox
          # Run additional commands to test the package


